# This file was generated by GoReleaser. DO NOT EDIT.
class Cyaml < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamhed/cyaml/releases/download/v0.1.0/cyaml_0.1.0_darwin_amd64.tar.gz"
    sha256 "9a3dc7343f1946208a90d93dc4583d30aa340c883114357b5e9840eba955e38c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/cyaml/releases/download/v0.1.0/cyaml_0.1.0_linux_amd64.tar.gz"
      sha256 "13d29488caa6bacb6dd442b94ca875991d44921408f9488e58a05dc561248353"
    end
  end

  def install
    bin.install "cyaml"
  end
end
