# This file was generated by GoReleaser. DO NOT EDIT.
class Cyaml < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamhed/cyaml/releases/download/v0.2.0/cyaml_0.2.0_darwin_amd64.tar.gz"
    sha256 "c393d2812c68ba729e984e71cd391e9a8b4867a62847774ea37e06a09967dfb7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/cyaml/releases/download/v0.2.0/cyaml_0.2.0_linux_amd64.tar.gz"
      sha256 "50c7ef754ed79df0622e4e59ee02b1c1e0dcd2adc57be6911c060e9854a65200"
    end
  end

  def install
    bin.install "cyaml"
  end
end
